added more test for Threat_intelligence module
stratosphereips/StratosphereLinuxIPS pull request #591
Opened 2024-05-30 14:50 UTC by Sekhar-Kumar-Dash

## Fixes Issue #590 

## Changes proposed

Added more tests for threat_intelligence

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2024-06-06 11:35 UTC, AlyaGomaa commented
the tests are failing because of the same issue here https://github.com/stratosphereips/StratosphereLinuxIPS/pull/593#issuecomment-2152142701

2024-06-07 15:37 UTC, AlyaGomaa commented
@Sekhar-Kumar-Dash for some reason the tests are failing in CI, let me know when they're fixed and i will review and merge

2024-06-08 13:43 UTC, Sekhar-Kumar-Dash commented
> @Sekhar-Kumar-Dash for some reason the tests are failing in CI, let me know when they're fixed and i will review and merge

okay looking at it

2024-06-11 00:13 UTC, AlyaGomaa reviewed
Thanks for all the hard work! @Sekhar-Kumar-Dash 
let me know when the changes are fixed and i will merge

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +def test_update_local_file(
we also need to test if appropriate handler functions we called, for example, JARM files shoudl result in a call to parse_jarm_file(), JA3 -> parse_ja3_file() , etc

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +def test_is_malicious_url(threatintel_obj, mocker):
we can use mark parametrize here

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +    mock_urlhaus_lookup = mocker.patch.object(threatintel_obj.urlhaus, "urlhaus_lookup")
why patch urlhaus_lookup() instead of search_online_for_url()?

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +    if expected_call == "is_malicious_cname":
always avoid if statements that check test cases if you're using mark parametrize. if statements render  mark.parametrize useless

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +    assert mock_ip_belongs_to_blacklisted_range.call_count == expected_calls["ip_belongs_to_blacklisted_range"]
line too long

2024-06-11 00:13 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +    mock_should_lookup = mocker.patch.object(
unused variable, we should have 2 cases, when should_lookup() is true and when its false

2024-06-11 00:19 UTC, AlyaGomaa commented
hey @Sekhar-Kumar-Dash how do you manage to get around this? i added a few comments but didnt modify your code and pre-commit hooks are preventing me from pushing because of your code, your code is already pushed so it should pass the hooks right?
![image](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/41242896/ec0c3501-8e31-40d4-a832-cd112da89108)


do you have pre-commit hooks disabled?

2024-06-11 15:43 UTC, Sekhar-Kumar-Dash commented on tests/test_threat_intelligence.py
> +def threatintel_obj(mock_db, tmp_path):
Sorry  At the time of writing the test, I just created this one and then I forgot about it

2024-06-13 09:38 UTC, AlyaGomaa commented on tests/test_threat_intelligence.py
> +    expected_calls,
@sekhar ?

2024-06-13 09:38 UTC, AlyaGomaa requested changes
please make sure all my comments are resolved before asking for a review again

2024-06-22 07:41 UTC, Sekhar-Kumar-Dash commented
@AlyaGomaa I had mistakenly deleted a part of the docstring for the circl_lu function. I have now fixed it.
please look at the earlier commit to know what other  changes i have made

2024-06-25 16:23 UTC, Sekhar-Kumar-Dash commented
I dont get it the test did passed the test locally

2024-06-26 10:56 UTC, AlyaGomaa commented
@Sekhar-Kumar-Dash the tests were passing locally for me too! weird! it was an issue with a missing space, will wait for the tests to pass and we'll see

2024-06-26 12:11 UTC, merged