added the  test for evidence.py
stratosphereips/StratosphereLinuxIPS pull request #771
Opened 2024-07-09 11:26 UTC by Sekhar-Kumar-Dash

## Fixes Issue #770 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2024-07-10 08:53 UTC, AlyaGomaa commented
hey @Sekhar-Kumar-Dash can you check why they're failing?

2024-07-22 16:06 UTC, AlyaGomaa commented on tests/module_factory.py
> +    def create_attacker_obj(value="192.168.1.1", direction=Direction.SRC, attacker_type=IoCType.IP):
All the added functions are missing "self" as first parameter

2024-07-22 16:06 UTC, AlyaGomaa requested changes
hey @Sekhar-Kumar-Dash can you fix this and update PR with the latest develop so i can see why CI is failing?

2024-07-22 17:31 UTC, Sekhar-Kumar-Dash commented
> hey @Sekhar-Kumar-Dash can you fix this and update PR with the latest develop so i can see why CI is failing?

hey @AlyaGomaa  okay i will make the required changes and then i will update the PR

2024-07-24 13:14 UTC, AlyaGomaa commented
hey @Sekhar-Kumar-Dash for some reason, the changes you made to evidence.py is what's causing CI to fail, i reverted them to the latest develop and will see how it goes

2024-07-25 14:12 UTC, merged