added test for output
stratosphereips/StratosphereLinuxIPS pull request #776
Opened 2024-07-11 08:39 UTC by Sekhar-Kumar-Dash

## Changes proposed

added tests for output

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2024-07-11 08:48 UTC, Sekhar-Kumar-Dash commented
@AlyaGomaa  can you take a look at test_create_logfile_new  am i doing it right

2024-07-30 14:14 UTC, AlyaGomaa requested changes
Hey @Sekhar-Kumar-Dash thanks for your effort! this PR needs small modifications to be able to merge it

2024-07-30 14:14 UTC, AlyaGomaa commented on tests/test_output.py
> +        output.pbar_sender_pipe.send.assert_called_once_with(
here we shouldnt be checking output.pbar_sender_pipe.send
pbar_sender_pipe.send() is not in the code of handle_printing_stats(), it is in the code of tell_pbar()
so we should be check tell_pbar() instead

2024-07-30 14:14 UTC, AlyaGomaa commented on tests/test_output.py
> +    output = ModuleFactory().create_output_obj()
here we can add a docstring saying that it didnt print because the given verbose (3) is more than the module's verbose (2)

2024-07-30 14:14 UTC, AlyaGomaa commented on tests/test_output.py
> +    output = ModuleFactory().create_output_obj()
because the function name is not enough to clarify this

2024-08-01 09:48 UTC, merged